#!/usr/bin/env bash
# Daily runner — fetch latest prices, regenerate report, commit + push.
# Designed to be invoked by a LaunchAgent or cron job.

set -euo pipefail

cd "$(dirname "$0")"
LOG_DATE=$(date +%Y-%m-%d)

echo "[$(date)] LLM Pricing daily run starting…"

python3 scripts/llm_pricing_fetch.py
python3 scripts/fetch_hunyuan.py

# regenerate HTML for today (idempotent if rerun)
python3 scripts/llm_pricing_report.py

# copy latest to index.html for GitHub Pages
TODAY_HTML="reports/${LOG_DATE}_llm_pricing.html"
if [[ -f "$TODAY_HTML" ]]; then
  cp "$TODAY_HTML" index.html
  echo "  → index.html updated from $TODAY_HTML"
fi

# commit + push if there are changes
if [[ -n "$(git status --porcelain)" ]]; then
  git add data/history.csv reports/ index.html
  git commit -m "daily snapshot ${LOG_DATE}" \
             -m "auto-generated by runner.sh"
  git push origin main
  echo "  → pushed to origin"
else
  echo "  → no changes to commit"
fi

echo "[$(date)] done."
